### ISSUE TITLE
Getting Error Add New Module

### ISSUE THREAD

**Issue by mochammadfawwaz** [gieart87/laravel8-bootstrap-ui-starter-app#13]
Success run the app but if i am add new module, the module will crash on my console

php artisan module:make <module-name> ( Bank )

See my screenshoot bro

![gambar](https://user-images.githubusercontent.com/22051898/141676827-5ae2f16f-8c7d-48ab-9e75-b88f7e2a22f5.png)

**Comment by gieart87** [comment]
Hi @mochammadfawwaz ,

Thanks for the feedback, let me take a look :)

**Comment by gieart87** [comment]
FYI @mochammadfawwaz , I've just fixed the issue that you've reported before. Please, pull the latest update for this repo. details, check here https://github.com/gieart87/laravel8-bootstrap-ui-starter-app/pull/14 . Thanks :)
